### ISSUE TITLE
Weird assert

### ISSUE THREAD

**Issue by RuiAAPeres** [Mantle/Mantle#326]
I am receiving the following:

`Invalid parameter not satisfying: [modelClass isSubclassOfClass:MTLModel.class]`

My class has the following header:

``` objc
@interface RPMessage : MTLModel <MTLJSONSerializing>

@end
```

Before using, where the code crashes:

``` objc
   RPMessage *message = [MTLJSONAdapter modelOfClass:[RPMessage class] fromJSONDictionary:json error:nil];
```

I am doing the following:

``` objc
NSLog(@"%@",[RPMessage superclass]);
```

And the output: `MTLModel`.

Any idea?

**Comment by akisute** [comment]
I ran into this issue as well, it's seemed to be the same reason of @Pretz. I have no idea it's a fault of cocoapods or Xcode, but basically I have to setup my Podfile like this:

```
pod 'lib1'
pod 'libTest'
```

You can not write a Podfile like this when you use Swift&Objc-Bridging-Header like this:

```
target "abc" do
  pod 'lib1'
end

target "abcTests" do
  pod 'libTest'
end
```

Because the setup above causes build error since you can't build Tests target as it also refers Objc-Briding-Header that uses lib1 while Tests target doesn't contain lib1, in this scenario.

**Comment by quantumpotato** [comment]
I have this issue when testing JSON parsing with manually constructed @{} dictionaries.
