### ISSUE TITLE
How to omit null value ?

### ISSUE THREAD

**Issue by wenzhaot** [Mantle/Mantle#343]
I have a model class SLVehicle.
```
+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{@"vid": @"id",
             @"brandName": @"brandName",
             @"modelName": @"modelName",
             @"follow": @"follow",
             @"certificated": @"certificated",
             @"vehicleNo": @"vehicleNo",
             @"plateNo": @"plateNo",
             @"plateType": @"plateType",
             @"engineNo": @"engineNo",
             @"drivingNo": @"drivingNo",
             @"classNo": @"classNo",
             @"cityNo": @"cityNo",
             @"typeName": @"type.name",
             @"typeLabel": @"type.label",
             @"remark": @"remark",
             @"statusName": @"status.name",
             @"statusLabel": @"status.label",
             @"nickName": @"nickName"};
}
```
The json string is
```
{
            "id": 5,
            "model": {
                "id": 1,
                "sort": 0,
                "name": "x7"
            },
            "brandName": "宝马",
            "modelName": "x7",
            "follow": false,
            "certificated": true,
            "vehicleNo": "23",
            "plateNo": "4234",
            "plateType": null,
            "engineNo": "234",
            "drivingNo": "234243",
            "classNo": null,
            "cityNo": null,
            "type": {
                "name": "CAR",
                "label": "四轮机动车"
            },
            "remark": "23424",
            "status": {
                "name": "APPROVE",
                "label": "已认证"
            },
            "nickName": "小萝卜头",
            "brandLogo": "4130"
        }
```
I found the pateType is null, so it's a NSNull class, I don't know how to change the NSNull to nil. Help me?

**Comment by chenyingsunny** [comment]
I overwrite dictionaryValue in my model, but the dictionaryValue method appears to never be called.

**Comment by chenyingsunny** [comment]
@tangqiaoboy 
in baseModel, overwrite 
-(void)setNilValueForKey:(NSString *)key
{
    [self setValue:@0 forKey:key];
}
for NSString, nil is OK，for a  scalar value, 0 is enough.

**Comment by robb** [comment]
Closing this one for lack of activity by the original author, feel free to reopen if need be.

**Comment by bartekhugo** [comment]
Approach with dictionaryValue doesn't seem to work...
This part from MLTJSONAdapter creates dictionary with nil values because of dictionaryWithValuesForKeys

NSSet *propertyKeysToSerialize = [self serializablePropertyKeys:[NSSet setWithArray:self.JSONKeyPathsByPropertyKey.allKeys] forModel:model];   
NSDictionary *dictionaryValue       = [model.dictionaryValue dictionaryWithValuesForKeys:propertyKeysToSerialize.allObjects];

**Comment by eytanbiala** [comment]
@robb What is the best way to approach this with Mantle 2.0?

**Comment by robb** [comment]
@eytanbiala can you file a new issue describing the problem you're having?

**Comment by eytanbiala** [comment]
@robb The issue is the same as the one here - how do we omit null values?

**Comment by robb** [comment]
@eytanbiala This issue is very old, has been marked as closed and has gotten kind of a mess. Please file a new one to make it easier to read and answer to it. From [this spec](https://github.com/Mantle/Mantle/blob/c32280d4dca32a646a4f30ff3b32aa7eae223500/MantleTests/MTLJSONAdapterSpec.m#L34-L60), it looks like we're already mapping `NSNull.null` to `nil` and back, can you describe your problem?
