### ISSUE TITLE
Header docs not parseable by Xcode/CocoaDocs

### ISSUE THREAD

**Issue by jshier** [Mantle/Mantle#394]
Currently the header docs aren't parseable by Xcode or CocoaDocs, which makes access a bit painful. Redoing the markup to make them compatible would be greatly appreciated.

**Comment by Ashton-W** [comment]
Is TomDoc still the prefered documentation style for Mantle?
Would a PR changing documentation to appledoc (or other) be considered?

**Comment by codiophile** [comment]
How relevant is TomDoc?

As a user of Mantle, the TomDoc formatting is not giving me any benefits. It only annoys me that the documentation is hard to read and not nicely formatted in Xcode.

I thought that maybe you are using TomDoc to generate some nice documentation somewhere, but I cannot find any links to any such documentation from the README and when I google "Mantle documentation", I'm also not finding any such documentation. 

The only argument for keeping the TomDoc format is that it is easier to read when looking at the header file. First of all, I don't agree with that. Reading the documentation in the headers of AFNetworking is at least just as easy, if not easier, and they are compatible with Xcode. Second I don't see how relevant that is. You shouldn't have to open the header file to know how to use a class. What is important is how easy it is to read when you alt-click, because that is much easier to use and saves you the pain of switching between source files.

I hope you will reconsider your choice of formatting and accept a pull request with updated documentation formatting, if someone is kind enough to provide it.

**Comment by robb** [comment]
Was the somewhat nicer syntax for docs that swift allows back-ported to Objective-C?

**Comment by jshier** [comment]
Yes, it's been compatible with Objective-C since day one.

I don't use Mantle any more (all Swift now), but I always found it pretty ridiculous that GitHub found it a good idea to standardize it's Objective-C documentation on a format completely incompatible with the tools used to develop said language. Hopefully you find the new documentation format good enough to use, to the benefit of Mantle users everywhere.
