### ISSUE TITLE
Concern about +classForParsingJSONDictionary: usage

### ISSUE THREAD

**Issue by manuyavuz** [Mantle/Mantle#526]
Hi, 

I have a concern about the usage of  `+classForParsingJSONDictionary` method. 

This method is very useful in cases where there is a JSON array containing object of different subclasses of a superclass.

Let's say we have `Animal` as superclass, and `Dog` and `Cat` as subclasses. 

```
@interface Animal : MTLModel

@end

@interface Cat : Animal

@end

@interface Dog : Animal

@end

```

In implementation of Animal class, what we would do is this:

```
#import "Cat.h"
#import "Dog.h"
...
@implementation Animal

+(Class)classForParsingJSONDictionary:(NSDictionary *)JSONDictionary {
    //Give some decision and set isCat value.
    ....
    if (isCat) {
        return [Cat class];
    }
    else {
        [Dog class];
    }
}

@end

```

Moving class selection decision into the superclass really facilitates the decision process. 

However, in this case we couple superclass to its subclasses because we have to import subclasses into superclass implementation, which is obviously a bad practice. 

I think we should find another way to handle this considering OOP principles. What do you think?

**Comment by robb** [comment]
> we have to import subclasses into superclass implementation,

Yeah, though I wonder if this can really be avoided with class clusters. 

> I think we should find another way to handle this considering OOP principles.

What do you have in mind?

**Comment by Ashton-W** [comment]
Instead of implementing `+classForParsingJSONDictionary:` in a base class, you can create a custom valueTransformer class that handles the decision and delegates the transformation to a specific MTLJSONAdapter.

The problem then is that you must use that transformer anywhere you would normally just use a MTLJSONAdapter.

Alternatively, just refactor the decision to a helper class, isolating the code that 'knows all'
```objc
+(Class)classForParsingJSONDictionary:(NSDictionary *)JSONDictionary {
    return [AnimalJSONHelper classForParsingJSONDictionary:JSONDictionary];
}
```

**Comment by nsforge** [comment]
One approach for dealing with the "super knows about subclasses" awkwardness is to use the Objective-C runtime to find all of the subclasses of `Animal`, then do something like this in `Animal`:
```
+(Class)classForParsingJSONDictionary:(NSDictionary *)JSONDictionary {
	for (Class aSubclass in subclassesFoundInRuntime) {
		if ([aSubclass canParseJSONDictionary:JSONDictionary]) return aSubclass;
	}
	return nil;
}
```
Then you can either declare `+canParseJSONDictionary:` method on `Animal` itself (and have subclasses override it, or you could create an `AnimalSubclass` protocol which declares `+canParseJSONDictionary:`, and make the subclasses adopt that protocol. If you went the protocol route, instead of enumerating `Animal` subclasses, you could enumerate classes that conform to `AnimalSubclass`.

This approach makes use of the Objective-C runtime, so depending on the context YMMV. You can also do a half-way approach where the subclasses themselves have the logic to "decide" if they can parse the dictionary, but the superclass has a hard-coded list of the subclasses to check.
