### ISSUE TITLE
Flag to disable validation

### ISSUE THREAD

**Issue by mojidabckuu** [Mantle/Mantle#563]
I have some issue with server side that I can't fix. For example `@""` values. I am using `validate<property name>:error:` to validate models in my application which Mantle uses also. They are intersect and it produces for me some pain to parse data and validate user input.

**Comment by robb** [comment]
I'm not sure I understand what your problem is, could you elaborate?

[`-validate<Key>:error:` is part of the Key-Value Coding mechanism](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/KeyValueCoding/Articles/Validation.html#//apple_ref/doc/uid/20002173-CJBDBHCB) at is automatically invoked from `-setValue:forKey:` which you cannot disable, as far as I know.

**Comment by mojidabckuu** [comment]
In Mantle exists two times validation process. 
1) In `-(void)validate` when we try to set value using KVC 
2) When it calls recursively `validateValue:forKey:`

So if I want remove validation on models I need override `validate` method in model that I parse and also `initWithDictionary:` to prevent  wrong values for my validation or inherit and override MTLJSONAdapter logic that is not good.

**Comment by robb** [comment]
Sorry, I'm still having trouble understanding why you want to disable validation.
