### ISSUE TITLE
How to debug which property is wrong type 

### ISSUE THREAD

**Issue by hilen** [Mantle/Mantle#604]
I got this error message 

```
Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Value did not match expected type" UserInfo=0x17186a380 {MTLTransformerErrorHandlingInputValueErrorKey=1, NSLocalizedDescription=Value did not match expected type, NSLocalizedFailureReason=Expected 1 to be of class NSString but got __NSCFNumber}
```

but how to know which property's type is wrong ?

**Comment by robb** [comment]
Try settings a breakpoint in `NSValueTransformer+MTLPredefinedTransformerAdditions.m:245` and inspect the stack of find for which property the transformer is being invoked.

I guess we could have the transformer capture the property name, but then we'd have one transformer per property, rather than property type.

**Comment by ilyawiz** [comment]
I encountered the same issue. Another solution would be to wrap the error from the transformer with additional context info. from the callstuck (class name, property key name, etc)
