### ISSUE TITLE
2.0.5 Update Causes Errors With Type (expected NSNumber got NSTaggedPointerString)

### ISSUE THREAD

**Issue by willlarche** [Mantle/Mantle#614]
The value is 49.97.

2.0.4 works fine but 2.0.5 causes an error in transforming.

**Comment by robb** [comment]
Can you share the JSON and property declaration/value transformers you're using?

**Comment by yurkins** [comment]
My code works excellent before update 2.0.3. 
The JSON is :  
```javascript 
{
      "id": 123,
      "type": "Place",
      "title": "Test place",
      "latitude": "40.4167754",
      "longitude": "-3.7037902"
}
```
In my case form version > 2.0.2 I received an error.
I think this happens because the numerical values come as string but once I set that properties is numeric then he must force transformation string to number, as it was up to version 2.0.2. I'm not a developer of the web service and I can't change any values or types in JSON.

>Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Value did not match expected type" 
UserInfo={MTLTransformerErrorHandlingInputValueErrorKey=-3.7037902, NSLocalizedDescription=Value did not match expected type, NSLocalizedFailureReason=Expected -3.7037902 to be of class NSNumber but got __NSCFString}
Printing description of _userInfo:
{
    *MTLTransformerErrorHandlingInputValueErrorKey = "-3.7037902";
    NSLocalizedDescription = "Value did not match expected type";
    NSLocalizedFailureReason = "Expected -3.7037902 to be of class NSNumber but got __NSCFString";*
}

**Comment by robb** [comment]
@yurkins I'm pretty sure that this didn't actually work pre `2.0.2`, you just didn't get an error.
E.g. when parsing something like

```objc
@interface Foo: MTLModel 

@property (readonly, nonatomic, strong) NSNumber *bar;

@end
```

your `bar` property would actually hold a `NSString`. This may have not produced any errors in production, since `NSNumber` and `NSString` have quite a bit of API in common (most notably, `doubleValue`) but that is not a reason not to introduce a value transformer.

**Comment by zhichaoLii** [comment]
maybe the reason is the apple api, the bar address maybe is point to 0x0, so when the pointer point to it and get the value from it,  it will crash

**Comment by tommybananas** [comment]
+1 im shocked this went so long undetected. Maybe try to convert and throw a warning?

**Comment by EvanLee** [comment]
@yurkins you can try this:

```
+ (NSValueTransformer *) longitudeJSONTransformer
{
    return [self floatTransformer];
}

+ (NSValueTransformer<MTLTransformerErrorHandling> *)floatTransformer {
    return [MTLValueTransformer
            transformerUsingForwardBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
                if ([value isKindOfClass:[NSString class]]) {
                    return @([value floatValue]);
                }
                
                return value;
            } reverseBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
                return value;
            }];
}

```

**Comment by opfeffer** [comment]
Running into the same problem when transforming an JSON NSDictionary to a NSMutableDictionary via `dict.mutableCopy`.

     Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Value did not match expected type" UserInfo=0x791952b0 {NSLocalizedFailureReason=Expected {
         v1 =     {
         };
     } to be of class NSMutableDictionary but got __NSDictionaryI, MTLTransformerErrorHandlingInputValueErrorKey={
         v1 =     {
         };
     }, NSLocalizedDescription=Value did not match expected type}

**Comment by robb** [comment]
@opfeffer would you mind creating a new issue?

**Comment by opfeffer** [comment]
Sure thing :+1:

**Comment by betzerra** [comment]
Any news with this guys?

**Comment by nikilster** [comment]
We're having the same issue (Crashing with error:  -[NSTaggedPointerString isEqualToNumber:]).  This is strange because we have multiple models converting to NSNumber and those are working fine.  

I think this is because we are using a field named "id" on this object.  Friend told me this is a keyword in iOS and Stack Overflow says it's still allowed to be safely used as a object property.  

Could this be related to why Mantle is sometimes not parsing a string into a NSNumber?

**Comment by nikilster** [comment]
(We're on 1.5.6)

**Comment by tommybananas** [comment]
I think @robb is correct, Mantle isn't actually doing these conversions for you. You need to explicitly transform `NSString` into `NSNumber`.

Something like this:
```
+ (NSValueTransformer *)numberTrasformer {
    return [MTLValueTransformer transformerWithBlock:^id(NSString *num) {
        return @(num.integerValue);
    }];
}
```

**Comment by nikilster** [comment]
Yup! We return numbers in our API and had a constants file which had numbers as string constants.  In almost all cases did intValue (which NSString and NSNumber have)  so it was fine most of the time.  We had one very occasional call to isEqualToNumber so that was the only place it crashed.  Thanks so much @tommybananas!

**Comment by robb** [comment]
I'll close this out since, if you have a similar issue in the future, please file a new issue. :smiley_cat:
