### ISSUE TITLE
iOS7

### ISSUE THREAD

**Issue by ghost** [Mantle/Mantle#666]
Why not support ios7？

**Comment by JanGorman** [comment]
How are you installing Mantle? It works just fine on iOS 7. If you use e.g. CocoaPods, the pod spec states that it supports iOS 5.0+: https://cocoapods.org/pods/Mantle

**Comment by vincentIOS** [comment]
I saw the introduction of Mantle，It shows
"System Requirements
Mantle supports OS X 10.9+ and iOS 8.0+."

**Comment by JanGorman** [comment]
Right on. Should probably be updated then… I'm using Mantle in a project that supports iOS7 so I can confirm that it does work :wink:

**Comment by dcaunt** [comment]
Mantle as a project officially supports OS X 10.9+ and iOS 8.0+ as described. This is due to the use of frameworks.

The is no code in Mantle which requires iOS 8 and this is why it works on iOS 7 (and older versions) however Mantle does not support installation via CocoaPods. Podspecs are contributed by third-parties.

**Comment by revolter** [comment]
@dcaunt, So, to make it more clear, if I manually install `Mantle` and not use CocoaPods, it 100% works on iOS 7 too?

**Comment by dcaunt** [comment]
If you include the source, it should work. If you embed the project as described in [README#importing-mantle](https://github.com/Mantle/Mantle#importing-mantle) and use the Framework target in the project, it won't.
