### ISSUE TITLE
Incomplete Bitcode Error during uploading the application on iTunes.

### ISSUE THREAD

**Issue by srjshinde1** [Mantle/Mantle#706]
Hello, 

We have used the Mantle V2.0.5 and using the Xcode 6.4 (used carthage for the same). Yesterday, while uploading application on iTunes store one issue appeared which states Incomplete bitcode.  Attached the screenshot of the same. Please help.
<img width="577" alt="screen shot 2016-06-02 at 12 23 45 am" src="https://cloud.githubusercontent.com/assets/4265739/15742231/45f6722e-28db-11e6-9bff-775b54ebbb6e.png">
the

**Comment by lvdaqian** [comment]
I have the same issue. But I am using Carthage, and the error occurs in greenhouse CI when try to publish build to itunes connect.

I have tried to build the framework directly by source code. the project setting for enable bitcode is on. But I still can't find the `segname __LLVM` by the command below:

```
otool -l /Users/wooko/Library/Developer/Xcode/DerivedData/Mantle-birpspoqwpwpzjggmnyqlmhskoev/Build/Products/Debug-iphoneos/Mantle.framework/Mantle | grep bitcode
```

is There something special to do ?

**Comment by Iyuna** [comment]
Had the similar issue building Overcoat framework. It depends on Mantle, so Carthage installed Mantle recent version 2.0.7. Received the following error during library linking process: `ld: bitcode bundle could not be generated because '/.../Mantle.framework/Mantle' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64`. Figured out that adding `--no-use-binaries` parameter to `carthage update` command fixed the issue. So it might be something wrong with Mantle binaries.
