### ISSUE TITLE
JSON Array OR Dictionary Transformer

### ISSUE THREAD

**Issue by chrisdhaan** [Mantle/Mantle#746]
I'm not sure if what I'm about to ask is currently possible in the Mantle project. I'm working with an older API that returns arrays of objects, but when only one object exists a dictionary is returned. This is causing my arrayTransformer methods to fail when a dictionary is returned for one object. I understand why the transformer is failing. My question is if there is a transformer than checks for either an array or a dictionary when transforming. Or is there some other way I can pull off this functionality using other methods in the Mantle project? Thanks.

**Comment by JanGorman** [comment]
Assuming that in your containing model you'd still have everything as arrays and that the key of the object is the same, you could use something like the following to pull that off:

```objective-c
+ (NSValueTransformer *)modelsJSONTransformer {
  return [MTLValueTransformer transformerUsingForwardBlock:^id(id value, BOOL *success, NSError **error) {
    if ([value isKindOfClass:[NSDictionary class]]) {
      return @[[MTLJSONAdapter modelOfClass:[ModelB class] fromJSONDictionary:value error:nil]];
    } if ([value isKindOfClass:[NSArray class]]) {
      return [MTLJSONAdapter modelsOfClass:[ModelB class] fromJSONArray:value error:nil];
    }
    return nil;
  }];
}
```
 So in your custom transformer you inspect the type and then if it's a dictionary use the appropriate transformer and wrap the result in an array. Otherwise use the straight up array transformer. For a JSON that looks like either this:

```json
{
  "key": "value",
  "models": {
    "key": "value"
  }
}
```

or this:

```json
{
  "key": "value",
  "models": [
    { "key": "value1"},
    { "key": "value2"}
  [
}
```

**Comment by chrisdhaan** [comment]
This is perfect. Exactly what I was trying to do. Thanks!
