### ISSUE TITLE
Remove escape character from JSON source

### ISSUE THREAD

**Issue by ZOlbrys** [Mantle/Mantle#755]
Hello,

I am parsing JSON data that sometimes contains escape characters for quotation marks, such as:

```
...
{
id = 13;
name = "5" Object";
},
...
```

Where I'd like my name property to be:

`5" Object`

However, it shows up as:

`5\" Object`

The model object for this JSON has the following `JSONKeyPathsByPropertyKey` method:

```
+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{@"identifier"              : @"id",
             @"name"                    : @"name"
             };
}
```

With no additional JSONTransformers being used.

Any ideas on how I'd be able to get the parsing of the name property done so that the escape character is removed?

Thanks!

**Comment by Abreu0101** [comment]
@ZOlbrys The character needs to be escaped because is in double quotes (`NSString` instance). At the moment of displaying to console or another `UIKit` element (ex. UILabel,etc), will be escaped correctly. Was there something specific that you wanted to do?

But in general to apply transformation, you have a few options:
`+ (NSValueTransformer *)keyNameJSONTransformer`
You replace `<keyName>` with the name of your property. In this method you need to return an NSValueTransformer instance, you could use MTLValueTransformer block based.

`+ (NSValueTransformer *)JSONTransformerForKey:(NSString *)key`
Same as before method, return an `NSValueTransformer` by `key` (property name).

`- (instancetype)initWithDictionary:(NSDictionary *)dictionaryValue error:(NSError *__autoreleasing *)error`
After initializing the instance, you could apply further cleanup in the properties.
