### ISSUE TITLE
Swift 3.0 - MTLJSONAdapter.modelOfClass

### ISSUE THREAD

**Issue by gunnartorfis** [Mantle/Mantle#775]
So I'm trying to use the modelOfClass method in the MTLJSONAdapter class but I'm not wrapping my head around this one.

This is what I have, surrounded by a do{} block.
`let user = try MTLJSONAdapter.model(of: User.class, fromJSONDictionary: userData) as! User`

The error I get is 
> Cannot convert value of type '([AnyHashable: Any]!) -> AnyClass!' to expected argument type 'AnyClass'!

I already read issue #421 but it doesn't seem to help me with Swift 3.0

Anyone that has any workarounds?

**Comment by JanGorman** [comment]
Is this a runtime or compile time issue? Not sure if it's just a typo in your sample but you should be calling it with `User.self`, not `.class`:

`let user = try MTLJSONAdapter.model(of: User.self, fromJSONDictionary: userData) as! User`

otherwise, could you post how you construct the dictionary. Though I believe it should work either way, as optional or unwrapped value…

**Comment by gunnartorfis** [comment]
Thanks for the quick reply. Calling it with User.self solved the issue.
