### ISSUE TITLE
Question on memory leaks with MTLValidateAndSetValue on xcode9 instrument

### ISSUE THREAD

**Issue by gupengno1** [Mantle/Mantle#818]
When i use xcode 9  instrument leak checks to test my app, I notice memory leaks when using

 `+ (id)modelOfClass:(Class)modelClass fromJSONDictionary:(NSDictionary *)JSONDictionary error:(NSError **)error;`

the root reason is function `[obj validateValue:&validatedValue forKey:key error:error]` in MTLValidateAndSetValue.

![image](https://user-images.githubusercontent.com/14288598/35024398-33ac88ce-fb7a-11e7-85c4-7ae04c78fc69.png)

![image](https://user-images.githubusercontent.com/14288598/35024384-25424e22-fb7a-11e7-89ab-3a1838efa29c.png)

**Comment by gupengno1** [comment]
can anyone help me to solve the problem~

**Comment by soranoba** [comment]
I could confirm similar things.
We can omit this validation in many cases, because Mantle already check basic types.
https://github.com/Mantle/Mantle/blob/6dae4d4617bfb7cfc7a2cc23b59738fb46b13157/Mantle/MTLJSONAdapter.m#L402-L419

So, I think that the easiest way is to implement the following in __all our model classes__.

```objc
- (BOOL)validateValue:(inout id  _Nullable __autoreleasing *)ioValue forKey:(NSString *)inKey error:(out NSError * _Nullable __autoreleasing *)outError{
  return YES;
}

- (BOOL)validate:(NSError *__autoreleasing *)error{
  return YES;
}
```

Please refer to https://github.com/Mantle/Mantle/issues/787#issuecomment-286608719

----

I don't know the root cause.
I think that it is a good option to report bugs to Apple.

**Comment by herrapa** [comment]
I have done some testing; it appears that this is a bug in the default implementation as @soranoba mentioned. 

This simple test leaks in iOS 11, but not in iOS 10. And if the method `validateValue:forKey:error:` is implemented as below, there are no leaks.

```objc
@interface TestClass : NSObject

@property NSString *testString;

@end

@implementation TestClass

/*
 If this method is implemented like this, leaks does not appear
 */
//- (BOOL)validateValue:(inout id  _Nullable __autoreleasing *)ioValue forKey:(NSString *)inKey error:(out NSError * _Nullable __autoreleasing *)outError {
//    return YES;
//}

@end

@implementation AppDelegate

- (void)applicationDidBecomeActive:(UIApplication *)application {
    [self testLeak];
}

#pragma mark -

- (void)testLeak {
    TestClass *testObject = [[TestClass alloc] init];
    NSError *error;
    NSString *testString = @"testValue";

    NSLog(@"Start");
    for (long i = 0; i < 100000000; i++) {
        [testObject validateValue:&testString forKey:@"testString" error:&error];
    }
    NSLog(@"End");
}
```
Since this is also a problem in MTLManagedObjectAdapter, where it validates values on NSManagedObjects, we cannot entirely solve the problem by implementing `validateValue:forKey:error:` in our Mantle model classes. 

I have reported this to apple.

**Comment by trickpirata** [comment]
Weird issue -- might be a bug with iOS 11 itself. Downloaded XCode 8.3.3 and now everything works fine. No issues with memory leaks whatsoever.

**Comment by FranciscoFortes** [comment]
I can reproduce the issue, but only on simulator using iOS 11. On device all is working as expected.

**Comment by MarsLeo** [comment]
I have such a problem, too. Have a solution
