### ISSUE TITLE
Unknown type name 'mtl_cleanupBlock_t' on Mantle 2.1.5 + libextobjc

### ISSUE THREAD

**Issue by stephenkopylov** [Mantle/Mantle#871]
Hello and thanks for this library! 

Found that 'pod update' updated Mantle to version 2.1.5 on which you'll face `Unknown type name 'mtl_cleanupBlock_t'` compile error when using libextobjc + Mantle 

Pod file:
```
target 'Test' do
  pod 'Mantle'
  pod 'libextobjc'
end

```

Test project:
[Test.zip](https://github.com/Mantle/Mantle/files/5379075/Test.zip)

**Comment by robb** [comment]
Weird, did this not happen to you before this update?

**Comment by stephenkopylov** [comment]
@robb At the moment I hardcoded Mantle to v2.1.4 in Podfile and it works good, but using just `pod ‘Mantle’` without setting the version you’ll get this error

**Comment by robb** [comment]
@defagos You reckon this could've happened in #870?

**Comment by defagos** [comment]
@robb Yes, this is very likely for some reason yet to be determined. Having only Mantle as a dependency works, but since libextobjc is also embedded internally (with name changes) the wrong header is apparently found if libextobjc is explicitly added as other dependency.

One possible fix is probably to rename the internal libextobjc files (mostly the headers) to avoid clashes with the real libextobjcy files. I'll have a look, sorry for this issue.

**Comment by defagos** [comment]
I [prefixed](https://github.com/SRGSSR/Mantle/commit/2d48fc6cb76ad15a06b9d55b802b4e294a2409ca) the internal libextobjc files with _MTL_ and this fixes the compilation issue when libextobjc is added as additional dependency in the Podfile.

I don't know how you usually test CocoaPods integration since the podspec is a JSON without version, which generates an error when running the pod command. To verify that the rename actually worked I added the version to the JSON podspec on a test branch and pushed it to my forked repository (for some reason local development pod integration seemed to work). 

I then pointed a test project at this branch, with libextobjc as additional dependency. The project fails to compile. Once I cherry-pick the commit linked above onto this branch, push the result and update the CocoaPods dependencies again, the project compiles fine.

If this fix proposal seems reasonable to you, I can propose this change as a PR we can test further together if you have a usual better test workflow than the one described above. Thanks in advance!

**Comment by stephenkopylov** [comment]
@defagos in my humble opinion, using prefixes is the best way to solve this

**Comment by robb** [comment]
@defagos Agreed, prefixing sounds good :+1:

**Comment by defagos** [comment]
Thanks @robb. As promised I opened a dedicated PR #872 to further discuss implementation details if needed.

**Comment by robb** [comment]
I merged and drafted [2.1.6](https://github.com/Mantle/Mantle/releases/tag/2.1.6) – @stephenkopylov can you confirm this addressed your issue?

**Comment by shmueldw** [comment]
Please update MTLManagedObjectAdapter, there are 'metamacros.h' file not found error

**Comment by defagos** [comment]
I didn't know about the [MTLManagedObjectAdapter](https://github.com/Mantle/MTLManagedObjectAdapter) repository, but still I had a look at potential problems with the file you mention.

The `metamacros.h` file is internal for this library as well, so I couldn't really understand why compilation would fail, especially since this dependency supports Carthage integration but not CocoaPods integration AFAIK. I still created a small `Cartfile` and could successfully build MTLManagedObjectAdapter 1.0 with Mantle 2.1.6 as dependency. I used Xcode 12 and the [workaround](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) required for Carthage.

I then added both generated frameworks to an iOS project and everything compiles fine. So I don't really understand your problem, I am afraid.
