### ISSUE TITLE
Can't install version 2.2.0 using pods

### ISSUE THREAD

**Issue by shmueldw** [Mantle/Mantle#891]
Hi, I can't install Mantle version 2.2.0 using pods.

> [!] CocoaPods could not find compatible versions for pod "Mantle":
>   In Podfile:
>     *** (from `../***`) was resolved to 1.1.0.1101, which depends on
>       Mantle (= 2.2.0)
> 
> None of your spec sources contain a spec satisfying the dependency: `Mantle (= 2.2.0)`.
> 
> You have either:
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.

The latest version that I able to install using pods is 2.1.6

Please help.

**Comment by JanGorman** [comment]
Unfortunately the two last versions weren't published to CocoaPods https://github.com/Mantle/Mantle/actions/workflows/cocoapods-publish.yml – and the logs aren't accessible anymore so at the moment there's no way to tell why they failed.

Would it be possible to talk to the author of whichever dependency has this hard requirement on 2.2.0. It's also a bit surprising to see this requirement since the author of that dependency couldn't have installed 2.2.0 themselves.

If we look at the [release notes](https://github.com/Mantle/Mantle/releases), technically 2.2 doesn't include anything new, it only raised the minimum iOS version requirement. So depending on which Xcode version you're using, 2.1.6 _might_ be enough.

**Comment by robb** [comment]
IIRC I looked into this briefly but I ran into problems getting the spec to validate.

I don't have a ruby environment set up and the Cocoapods app's bundled `pod` seems to be too old.

**Comment by JanGorman** [comment]
I just remembered that there was an issue with CocoaPods in April that required everyone to log in again and/or regenerate their `COCOAPODS_TRUNK_TOKEN`: https://blog.cocoapods.org/CocoaPods-Trunk-RCE/

I have a ruby env setup, I can dig further sometime in the coming days.

**Comment by mkjhgfdsa123** [comment]
诚聘网络兼职工资日结!还不~错详情请登陆招聘网站http://brhlqvy.cn?9

**Comment by robb** [comment]
I think @JanGorman just released a new pod – @shmueldw can you confirm it's working and close out the issue?

**Comment by JanGorman** [comment]
@robb Indeed, was just about to comment 😬. I manually pushed it since the `${GITHUB_REF/refs\/tags\//}` doesn't resolve to the right thing if run from master. The _next_ version _should_ be ok though. The `COCOAPODS_TRUNK_TOKEN` is up to date.

**Comment by robb** [comment]
Thanks a lot!
