### ISSUE TITLE
Mantle crashes on iOS 16  due to WorkflowKit containing an unprefixed Mantle copy

### ISSUE THREAD

**Issue by ycarmeli** [Mantle/Mantle#893]
Seems pretty random.

**Comment by evandorn** [comment]
As of iOS16 I am also getting some crashes 

`*** Assertion failure in +[MTLJSONAdapter dictionaryTransformerWithModelClass:], /Volumes/myproject/Pods/Mantle/Mantle/MTLJSONAdapter.m:478
`
`** Caught exception Invalid parameter not satisfying: [modelClass conformsToProtocol:@protocol(MTLModel)]
`
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [modelClass conformsToProtocol:@protocol(MTLModel)]
`
Works fine on iOS 15 and below. I am still working on trying to diagnose what causes this. Not sure if these are the same crashes you see in the debugger + logs @ycarmeli?

**Comment by robb** [comment]
it is

**Comment by robb** [comment]
Long story short, Manle is used by `WorkflowKit` which seems to get loaded into the app process, bringing its copy of Mantle along. This results in two protocols of the same name in the runtime which trips our assert – I assume there's nothing in terms of order guarantees here which probably causes this to happen randomly.

I've brought this to Apple's attention and hope they resolve the issue ASAP. There's nothing we can do here short of renaming all Mantle classes 😬

**Comment by robb** [comment]
@evandorn @ycarmeli This should be fixed as of Beta 3 – can you confirm?

**Comment by evandorn** [comment]
@robb Yes, this appears to be resolved as of the latest Xcode Beta 3 for me. Thanks for the help with this @robb!

**Comment by robb** [comment]
Great, thanks everyone!
